### ISSUE TITLE
issue while loading DICOM files: Unable to find file or directory 'resources/head.mat'

### ISSUE THREAD

**Issue by Din0-3** [Beastmaster/spine-curve#1]
Hi 

Thank you for sharing your code with GUI

When I was trying to run in within matlab I encountered several issues 

first when I click the load button I noticed there seems to be a default directory that is not present in the files `(D:|Project|spine_seg_spline\temp|test_dcm_531\*.dcm)`

by manually switching to all files the dicom files appeared in the GUI successfully but several other errors showed up,  as follows 
```matlab
Warning: File and dictionary VR values do not match for attribute "TargetExposureIndex"
(0018,1412). Expected: DS. Found: UN. Consider setting the 'UseDictionaryVR' parameter to true. 
> In dicominfo>convertRawAttr (line 152)
In dicominfo>processMetadata (line 114)
In dicominfo (line 72)
In Draw_Spine_Curve>open_Btn_Callback (line 132)
In gui_mainfcn (line 95)
In Draw_Spine_Curve (line 42)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)Draw_Spine_Curve('open_Btn_Callback',hObject,eventdata,guidata(hObject)) 
Error using load
Unable to find file or directory 'resources/head.mat'.

Error in GrayScaleBased>strip_head_pelvis (line 431)
    head = load('resources/head.mat');

Error in GrayScaleBased>process (line 133)
rc = strip_head_pelvis(img_ori,'head');%pos = int16(pos/2);

Error in GrayScaleBased (line 100)
    [curve,fusion]= process(varargin{2});

Error in Draw_Spine_Curve>open_Btn_Callback (line 149)
    [handles.Curve,handles.Bin_Image] = GrayScaleBased('process',handles.Ori_Image);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in Draw_Spine_Curve (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)Draw_Spine_Curve('open_Btn_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.
``` 

I'm not familiar with matlab language but I've noticed there is no such file `'resources/head.mat'` present within the source code

Is that causing the problem ?

Thanks a lot !

Dino

**Comment by Beastmaster** [comment]
"resource/head.mat" is private data so I couldn't put it on github. While, "head.mat" is just a gray scale image patch acquired from averaging multiple images of "human head". The image patch is used to match "head" position of incoming image. A correlation operation is performed in a convolutional way so you can locate "head" by finding the maxmium correlation score.

**Comment by Din0-3** [comment]
Hi
thanks for your response, I see.
dose it means that I can produce the file by myself by acquiring multiple human skull X ray image and run the remaining script ?
Are there any specific requirements ?

thank you!

**Comment by Beastmaster** [comment]
Yes, sure. You may collect multiple scans and align them manually to get a better template. 
FYI: If you just want to go through the pipeline, you can skip loading "head" template and replace the step with a user defined boudingbox

**Comment by Din0-3** [comment]
hi, still trying to figure that out but thanks !
